spring:
  datasource:
      name: druidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      sql-script-encoding: utf-8
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/jpademo?allowMultiQueries=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化时建立物理连接的个数
        initial-size: 5
        # 最小连接池数量
        min-idle: 5
        # 最大连接池数量
        max-active: 50
        # 配置获取连接等待超时的时间
        max-wait: 30000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-while-idle: true
        # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-borrow: false
        # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
        test-on-return: false
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 50
server:
  port: 8083
  tomcat:
      max-http-header-size: 8192